version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      # Cloudflare Access Service Auth
      - VITE_CF_CLIENT_ID=${VITE_CF_CLIENT_ID}
      - VITE_CF_CLIENT_SECRET=${VITE_CF_CLIENT_SECRET}
      - VITE_CF_ACCESS_TOKEN=${VITE_CF_ACCESS_TOKEN}
    command: npm run dev

  docker-daemon:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""  # Disable TLS for simplicity
    command: ["dockerd", "--host=tcp://0.0.0.0:2376", "--host=unix:///var/run/docker.sock"]
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DOCKER_HOST=tcp://docker-daemon:2376
      - NODE_ENV=development
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,https://localhost:3000}
    depends_on:
      docker-daemon:
        condition: service_healthy
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload 