version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_CF_CLIENT_ID=${VITE_CF_ACCESS_CLIENT_ID}
        - VITE_CF_CLIENT_SECRET=${VITE_CF_ACCESS_CLIENT_SECRET}
        - VITE_CF_ACCESS_TOKEN=${VITE_CF_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    environment:
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_API_URL=${VITE_API_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      # Cloudflare Access Service Auth
      - VITE_CF_CLIENT_ID=${VITE_CF_ACCESS_CLIENT_ID}
      - VITE_CF_CLIENT_SECRET=${VITE_CF_ACCESS_CLIENT_SECRET}
      - VITE_CF_ACCESS_TOKEN=${VITE_CF_ACCESS_TOKEN}
    depends_on:
      - backend

  docker-daemon:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""  # Disable TLS for simplicity
    command: ["dockerd", "--host=tcp://0.0.0.0:2376", "--host=unix:///var/run/docker.sock"]
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DOCKER_HOST=tcp://docker-daemon:2376
      - BACKEND_URL=${BACKEND_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    depends_on:
      docker-daemon:
        condition: service_healthy 